#!/bin/bash
# Looks for changes to Gemfile[.lock] and automates running bundle and other tasks.

function changed {
  git diff --name-only HEAD@{2} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'Gemfile.*'; then
  echo "Gemfile changed, bundling"
  bundle install
  [[ -d 'tmp' ]] && touch 'tmp/restart.txt'
fi

if changed 'db/migrate'; then
  echo "Migrations pending, migrating"
  bundle exec rake db:migrate RAILS_ENV=development
  bundle exec rake db:migrate RAILS_ENV=test
  # bundle exec rake db:migrate RAILS_ENV=production
  [[ -d 'tmp' ]] && touch 'tmp/restart.txt'
fi
